version: '3'
services:
  node-devops:
    build: 
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword  
    volumes:
      - mongo-db:/data/db  

volumes:
  mongo-db: