version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  node-devops:
    build: 
      context: .
      target : dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=dev
      - MONGO_PASSWORD=mypassword
    command : yarn dev

  
