version: '3'
services:
  nginx:
    ports:
      - "80:80"

  node-devops:
    build: 
      context: .
      target: prod
    environment:
      - NODE_ENV=production
    command : node ./server.js

